purity-ploidy-estimator/src/main/resources/r/somaticVariantPlots.R

We were getting a random `Rplots.pdf` file corresponding to the `somatic.clonality.png` plot.
I _think_ it's because of this line.

Remove lonely clonalityModelPlot object

---

gripss/src/main/kotlin/com/hartwig/hmftools/gripss/GripssConfig.kt

GRIPPS's failing when the input VCF is a relative file path in CWD, e.g. `-output_vcf gridss.somatic.vcf.gz`, because `File("gridss.somatic.vcf.gz").parentFile` is null.
Adding an extra `absoluteFile` fixes the issue.
Vlad

GRIPPS: Fix NullPointerException when -output_vcf is a file name in CWD

---

patient-db/src/main/java/com/hartwig/hmftools/patientdb/clinical/ClinicalAlgoConfig.java
patient-db/src/main/java/com/hartwig/hmftools/patientdb/clinical/SampleLoader.java
patient-db/src/main/java/com/hartwig/hmftools/patientdb/clinical/context/ProductionRunContextFactory.java
patient-db/src/main/java/com/hartwig/hmftools/patientdb/clinical/readers/RunsJsonReader.java
patient-db/src/test/java/com/hartwig/hmftools/patientdb/clinical/readers/RunsJsonReaderTest.java
patient-db/src/test/resources/context/RunJson/two_somatic.json

Adds a simple json deserializer which takes a local file and creates a list of run
contexts. Will be used when the run_dir argument is null and the run_json argument is
specified.

DEV-1853 Create list of runcontexts from json when specified

---

patient-db/src/main/java/com/hartwig/hmftools/patientdb/clinical/ClinicalAlgoConfig.java

The change that was made previously to allow a JSON file containing the
runs (instead of a runs directory) could only be unit tested. However
when run in-app there was a check against the runs directory that was
still breaking the in-GCP clinical loader.
This change loosens the argument checking to allow the SampleLoader
class to do all the checking. It knows about both arguments and will
require one and only one of the runs JSON/runs directory to be given.

DEV-1827 Loosen initial required args checks

---

patient-reporter/pom.xml

This is required when including it as a dependency in the GCP wrapped version.

DEV-2199 Backport shading for patient-reporter JAR

---

orange/src/main/java/com/hartwig/hmftools/orange/report/chapters/CohortComparisonChapter.java

Since this file is optional, maybe this is tidier than having external scripts do the same check.

DEV-2355 Skip adding the separate feature plot if the file doesn't exist

---

patient-db/src/main/resources/generate_database.sql
patient-db/src/main/resources/patches/patientdb/patientdb3.62_to_3.63_migration.sql

SomaticVariant, geneCopyNumber, copyNumber and structuralVariant. A couple column size reductions also
necessary such that the index will fit into the max for mysql.
Applied in both a patch and generate_database.sql.

DEV-2333 Add unique keys for large genomic db tables

---

hmf-id-generator/src/test/kotlin/com/hartwig/hmftools/extensions/cli/options/commands/CommandOptionTest.kt
patient-reporter/src/main/java/com/hartwig/hmftools/patientreporter/PatientReport.java
patient-reporter/src/main/java/com/hartwig/hmftools/patientreporter/PatientReporterApplication.java
patient-reporter/src/main/java/com/hartwig/hmftools/patientreporter/algo/AnalysedPatientReport.java
patient-reporter/src/main/java/com/hartwig/hmftools/patientreporter/algo/AnalysedPatientReporter.java
patient-reporter/src/main/java/com/hartwig/hmftools/patientreporter/cfreport/ReportResources.java
patient-reporter/src/main/java/com/hartwig/hmftools/patientreporter/cfreport/chapters/analysed/DetailsAndDisclaimerChapter.java
patient-reporter/src/main/java/com/hartwig/hmftools/patientreporter/cfreport/chapters/failed/QCFailDisclaimerChapter.java
patient-reporter/src/main/java/com/hartwig/hmftools/patientreporter/cfreport/components/SidePanel.java
patient-reporter/src/main/java/com/hartwig/hmftools/patientreporter/qcfail/QCFailReport.java
patient-reporter/src/main/java/com/hartwig/hmftools/patientreporter/qcfail/QCFailReporter.java
patient-reporter/src/main/java/com/hartwig/hmftools/patientreporter/reportingdb/ReportingDb.java
patient-reporter/src/test/java/com/hartwig/hmftools/patientreporter/ExampleAnalysisTestFactory.java
patient-reporter/src/test/java/com/hartwig/hmftools/patientreporter/algo/AnalysedPatientReporterTest.java
patient-reporter/src/test/java/com/hartwig/hmftools/patientreporter/cfreport/CFReportWriterTest.java

This static field is being used as a global variable for the generation date
of the patient report. It's causing a bug in the GCP-based reporting because
in that situation the process remains running for quite a long time and the
static date drifts from the current date.
Eliminate this global variable in favour of a parameter to the reports that
is injected at the top level. Since it's no longer static the value of this
can be set each time the `.main()` method is called by the controlling
process.
Also in an only tangentially related change I've modified the test for
`CommandOption.kt` as this does not work on Linux, the `cd` command it was
using for a command that should exist does not actually exist as a
standalone executable on Linux. `more` should be available as a binary on
Windows, …

DEV-2408 Remove static date from ReportResources

---

orange/src/main/java/com/hartwig/hmftools/orange/conversion/OrangeConversion.java
orange/src/test/java/com/hartwig/hmftools/orange/conversion/OrangeConversionTest.java
orange/src/test/java/com/hartwig/hmftools/orange/conversion/TestCommonDatamodelFactory.java
pom.xml

Add the two missed fields and also handle the nullable interpretation field.
Adds a test as well which asserts for an empty, minimal, and exhaustive test datamodel. If we like how this test looks will add the same for the other converted datamodel classes.

DEV-3251 Fix the orange conversion for virus interpretation

---

hmf-common/src/main/java/com/hartwig/hmftools/common/isofox/GeneExpressionDistributionData.java
orange/src/main/java/com/hartwig/hmftools/orange/algo/isofox/ExpressionSelector.java
orange/src/test/java/com/hartwig/hmftools/orange/algo/isofox/ExpressionSelectorTest.java

The cohort isn't indicated when ingesting the isofox results but we can detect the special n/a value of -1. When this isn't provided, there is no filtering on cohort percentile so the number of genes meeting the expression thresholds is expected to be higher.

ACTIN-151: Fix expression selection bug for unknown cohort

---

patient-db/src/main/resources/generate_database.sql
pom.xml

The camelCase table names are changed into upper case by jOOQ since that is the default of underlying H2 database implementation. Wrapping names in backticks avoids this.

DEV-3605 Add backticks for jOOQ code generation

---

orange/README.md
orange/src/main/java/com/hartwig/hmftools/orange/report/chapters/FrontPageChapter.java

Small change, adds UGT1A1 directly under DPYD on front page of report in same format.
Testing manually with ReportGeneratorTestApplication, outputs "*1_HOM (Normal Function)" also for this gene.

ACTIN-324: add UGT1A1 status to front page of orange report

---

orange-datamodel/src/main/java/com/hartwig/hmftools/datamodel/LocalDateAdapter.java
orange-datamodel/src/main/java/com/hartwig/hmftools/datamodel/OrangeJson.java
pom.xml

When using orange-datamodel in jdk17, reflection errors on LocalDate cause json serialization errors. This adds a type adapter to fix the problem. The json file itself maintains the same format:
```json
"experimentDate": {
"year": 2022,
"month": 1,
"day": 20
},
```

Actin 333: orange-datamodel jdk17 support

---

hmftools-build.py

- Cleaned up hmftools-build.py and added some documentation to make it more clear what the script does.
- Resulting builds will now not include the 'v' prefix, so `git tag orange-v1.0.0` will build an orange artifact with version `1.0.0`.
- The 'v' is now mandatory in the git tag, this is to ensure that it is impossible accidentally create two conflicting git tags for the same version I.E. orange-v1.0.0 and orange-1.0.0.

DEV-3374 refactor hmftools-build and solve 'v' prefix issue

---

orange/src/main/java/com/hartwig/hmftools/orange/report/chapters/FrontPageChapter.java

Tiny fix to report formatting.

ACTIN-349: format SVs on Orange front page as percentile not percentage

---

orange-datamodel/src/main/java/com/hartwig/hmftools/datamodel/linx/LinxBreakend.java
orange-datamodel/src/test/java/com/hartwig/hmftools/datamodel/OrangeJsonTest.java
orange/src/main/java/com/hartwig/hmftools/orange/conversion/LinxConversion.java

Simple change, see ticket for rationale

ACTIN-353: Remove strand field from LinxBreakend ORANGE datamodel

---

hmftools-build.py

This should address the issue discovered in https://console.cloud.google.com/cloud-build/builds;region=europe-west4/c97c6129-b807-46df-852e-e42457b7d04d;step=0?project=hmf-build

INFRA-204 make program exit if maven build fails

---

patient-db/pom.xml
patient-db/src/main/java/com/hartwig/hmftools/patientdb/CheckSampleAbsentFromDatabase.java
patient-db/src/main/java/com/hartwig/hmftools/patientdb/CheckSampleExistsInDatabase.java
patient-db/src/main/java/com/hartwig/hmftools/patientdb/DeleteSampleFromDatabase.java
patient-db/src/main/java/com/hartwig/hmftools/patientdb/LoadCanonicalTranscripts.java
patient-db/src/main/java/com/hartwig/hmftools/patientdb/LoadChordData.java
patient-db/src/main/java/com/hartwig/hmftools/patientdb/LoadCiderData.java
patient-db/src/main/java/com/hartwig/hmftools/patientdb/LoadCuppa.java
patient-db/src/main/java/com/hartwig/hmftools/patientdb/LoadCuppa2.java
patient-db/src/main/java/com/hartwig/hmftools/patientdb/LoadDriverGenePanel.java
patient-db/src/main/java/com/hartwig/hmftools/patientdb/LoadFlagstatData.java
patient-db/src/main/java/com/hartwig/hmftools/patientdb/LoadLinxData.java
patient-db/src/main/java/com/hartwig/hmftools/patientdb/LoadMetricsData.java
patient-db/src/main/java/com/hartwig/hmftools/patientdb/LoadPeachData.java
patient-db/src/main/java/com/hartwig/hmftools/patientdb/LoadPurpleData.java
patient-db/src/main/java/com/hartwig/hmftools/patientdb/LoadSignatures.java
patient-db/src/main/java/com/hartwig/hmftools/patientdb/LoadTealData.java
patient-db/src/main/java/com/hartwig/hmftools/patientdb/LoadVirusBreakendData.java
patient-db/src/main/java/com/hartwig/hmftools/patientdb/LoadVirusInterpreter.java

Several small improvements and additions to patient-db that make it possible to run the loader classes as separate processes in an automated way:
* Let all loaders return exit code `1` on failure.
* Let all loaders use try-with-resources to close the database connection on failure.
* Add class `CheckSampleExistsInDatabase`, which is used by automation to check whether a sample already exists.
* Add a `-sample` parameter to `LoadCuppa2`. Using the TSV header doesn't work since that's often just "sample_1" instead of the real sample ID.
Also removed the "shade" profile, which is no longer needed when the `patient-db.jar` is run as a separate process.

INFRA-266 Improve patient-db loaders

---

orange/README.md
orange/src/main/java/com/hartwig/hmftools/orange/algo/OrangeAlgo.java
orange/src/main/java/com/hartwig/hmftools/orange/algo/sage/GermlineMVLHFactory.java
orange/src/main/java/com/hartwig/hmftools/orange/report/chapters/GermlineFindingsChapter.java
orange/src/main/java/com/hartwig/hmftools/orange/report/tables/GermlineLossOfHeterozygosityTable.java
orange/src/main/java/com/hartwig/hmftools/orange/report/tables/MissedVariantLikelihoodTable.java
orange/src/test/java/com/hartwig/hmftools/orange/algo/OrangeAlgoTest.java
orange/src/test/java/com/hartwig/hmftools/orange/algo/sage/GermlineMVLHFactoryTest.java

Changes:
- Remove unneeded division by 100 from when the input file contained percentages instead of factors.
- There are genes that have MVLH 100% and depth 0 in the input file due to being ignored by SAGE germline entirely. Remove these genes from both the MVLH table in the PDF and the related field in the JSON.
Please feel free to add more reviewers if you want.
I couldn't think of a better way to do the test I added to OrangeAlgoTest. If you can, please let me know.

DEV-3766: Fix germline MVLH table in PDF

---

orange/src/main/java/com/hartwig/hmftools/orange/cohort/mapping/CohortConstants.java
pom.xml

Added the combination of DOID 3738 (esophageal squamous cell carcinoma) and 0080374 (gastroesophageal cancer) to  the explicit list of doid combinations to be mapped to esophageal cohort

INFRA-347: Support unusual esophageal DOID configuration in cohort mapping

---

compar/src/main/java/com/hartwig/hmftools/compar/ItemComparer.java
compar/src/main/java/com/hartwig/hmftools/compar/chord/ChordComparer.java
compar/src/main/java/com/hartwig/hmftools/compar/common/CommonUtils.java
compar/src/main/java/com/hartwig/hmftools/compar/cuppa/CuppaComparer.java
compar/src/main/java/com/hartwig/hmftools/compar/driver/DriverComparer.java
compar/src/main/java/com/hartwig/hmftools/compar/lilac/LilacComparer.java
compar/src/main/java/com/hartwig/hmftools/compar/linx/DisruptionComparer.java
compar/src/main/java/com/hartwig/hmftools/compar/linx/DisruptionData.java
compar/src/main/java/com/hartwig/hmftools/compar/linx/FusionComparer.java
compar/src/main/java/com/hartwig/hmftools/compar/linx/GermlineSvComparer.java
compar/src/main/java/com/hartwig/hmftools/compar/linx/GermlineSvData.java
compar/src/main/java/com/hartwig/hmftools/compar/mutation/GermlineVariantComparer.java
compar/src/main/java/com/hartwig/hmftools/compar/mutation/GermlineVariantData.java
compar/src/main/java/com/hartwig/hmftools/compar/mutation/SomaticVariantComparer.java
compar/src/main/java/com/hartwig/hmftools/compar/purple/CopyNumberComparer.java
compar/src/main/java/com/hartwig/hmftools/compar/purple/GeneCopyNumberComparer.java
compar/src/main/java/com/hartwig/hmftools/compar/purple/GermlineDeletionComparer.java
compar/src/main/java/com/hartwig/hmftools/compar/purple/PurityComparer.java
hmf-common/pom.xml
hmf-common/src/main/java/com/hartwig/hmftools/common/genome/position/GenomePositionImpl.java

Liftover was only being done for somatic variants when reading from file. Now will be done for somatic and germline variants and disruptions when reading from file or SQL DB.
Also remove strict requirement that transcript IDs are equal for matching somatic disruptions against each other, since this caused unnecessary mismatches when comparing 37 vs 38. Instead of always matching transcript IDs, always match gene names and skip transcript ID matching when the transcripts are both canonical.

DEV-3784: Expand Liftover in Compar

---

orange/src/main/java/com/hartwig/hmftools/orange/algo/OrangeAlgo.java

LILAC pre v1.6 used to write fragment counts to ref fields in case it was run in tumor-only mode. This has been fixed in LILAC v1.6, and since we depend on that now, we can remove the work-around for this in ORANGE.
With this change, ORANGE assumes tumor fragments are filled in when run in tumor-only mode. 
Have tested using COLO829 tumor+ref and tumor-only.

ACTIN-999: Remove pre-LILAC v1.6 check from ORANGE

---

hmf-common/src/main/java/com/hartwig/hmftools/common/isofox/IsofoxDataLoader.java
orange/README.md
orange/src/main/java/com/hartwig/hmftools/orange/algo/OrangeAlgo.java
pom.xml

Note: Have tested 3.4.0 vs 3.5.1 on:
- Sample with orange type "Ovary/Fallopian tube"
- Sample with orange type "Esophagus"
- Sample with orange type "Unknown"

ACTIN-1010: Add workaround for some orange to isofox cancer type mappings

---

orange/README.md
orange/src/main/java/com/hartwig/hmftools/orange/algo/cuppa/CuppaDataFactory.java
orange/src/test/java/com/hartwig/hmftools/orange/algo/cuppa/CuppaDataFactoryTest.java
pom.xml

Have tested on data-vm and confirmed this ORANGE version creates a JSON file which can be ingested into ACTIN (no NaN exception anymore).

ACTIN-1057: Filter NaN likelihoods from CUPPA when converting in ORANGE

---

cloudbuild.yaml
hmftools-build.py
orange/Dockerfile

Add the creation of a Docker container to the building of `hmftools` modules. Does not do the Docker part if there is no Dockerfile for the module.
I've leveraged the Python script to do the heavy lifting but since the containers used in the build environment are quite modular I opted to generate the Docker-related commands for execution by a subsequent stage. I feel given the simplicity of the build overall this is acceptable.

INFRA-541 Build Orange Docker container

---

cloudbuild.yaml
hmftools-build.py

Rather than the PAT (personal access token) linked to my account, switch to using this flow meant for the Github "app" capability.
For testing I configured an app in Github and granted it the required permissions on one of my personal repositories. I generated a private key for it and used the client id and installation id metadata to test the flow implemented in the code.
In the code there is a change to read the private key rather than the PAT, and this has been parameterised instead of hardcoded. The client and installation ids are also passed in are used in conjunction with the private key to generate a JWT, which is then used to fetch a short-lived token. That token can then be used in the same way as the PAT.
I have also modified the cloudbuild file, a new secret will have to be …

INFRA-653 Switch to Github app authentication

---

orange/README.md
orange/src/main/java/com/hartwig/hmftools/orange/algo/purple/SomaticVariantSelector.java
orange/src/test/java/com/hartwig/hmftools/orange/algo/purple/SomaticVariantSelectorTest.java

A few weeks ago I noticed (due to an ORANGE report I was reviewing before sharing) that we were stating in the README in the “Other potentially relevant variants” section: _"**Exonic** variants that are not reported but are phased with variants that are reported"_, but in code we were actually not checking for exonic/intronic. Therefore I removed "Exonic" from the README to be in line with our code, but I do think it would be better to only show exonic variants on the report, so I added this logic now

ACTIN-1142: Ensure only exonic variants that are phased with reported variants are shown in ORANGE
